version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ourstorybook_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: dinhthai2004
      MYSQL_DATABASE: ourstorybook
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pdinhthai2004 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    image: theodorescsa/ezpdf-lib-requirements:latest
    container_name: ourstorybook_web
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py shell < create_superuser.py &&
        python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: ourstorybook_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped

volumes:
  db_data:
