# Generated by Django 4.2.6 on 2024-07-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
                ('published', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.genresmodel')),
            ],
        ),
    ]
