# Generated by Django 4.2.6 on 2024-07-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_bookmodel_genres_bookmodel_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
