# Generated by Django 5.1.4 on 2024-12-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bookmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=200)),
                ('page_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_pages', to='home.bookmodel')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
    ]
