# Generated by Django 5.1.4 on 2024-12-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bookmodel_updated_at_pagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='chapter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
