# Generated by Django 5.1.4 on 2025-02-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_purchasedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='price_at_purchase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
