# Generated by Django 5.1.4 on 2025-02-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_purchasedbook_price_at_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
