# Generated by Django 5.1.4 on 2025-03-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_purchasedbook_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
